title: Jonah Snider
description: > # this means to ignore newlines until "baseurl:"
  High school student. Computers, programming, hacking.
baseurl: ""
url: "https://pizzafox.github.io"
permalink: /:year/:month/:day/:title
repository: PizzaFox/pizzafox.github.io

# Extra information
github_profile: "https://github.com/PizzaFox"
user: "Jonah Snider"
user_email: "me@jonahsnider.ninja"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
