title: Jonah Snider
description: > # this means to ignore newlines until "baseurl:"
  High school student. Computers, programming, hacking.
baseurl: ""
url: "https://pizzafox.github.io"
permalink: /:year/:month/:day/:title

# Extra information
github_profile: "https://github.com/PizzaFox"
author: Jonah Snider
user_email: "me@jonahsnider.ninja"
twitter:
  username: thepizzafox

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-seo-tag
future: true
