#
# WEBSITE INFORMATION
#

# Website information
title: Jonah Snider
description: Freelance full stack developer
url: "https://jonahsnider.ninja"

#
# BUILD CONFIGURATION
#

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-seo-tag
  - html-proofer
future: true
include: ["_headers"]
