title: Jonah Snider
description: > # this means to ignore newlines until "baseurl:"
  High school student. Computers, programming, hacking.
baseurl: "/matjek-personal"
url: "https://pizzafox.github.io"
permalink: /:year/:month/:day/:title
repository: PizzaFox/matjek-personal
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/PizzaFox"
user: "Jonah Snider"
user_email: "me@jonahsnider.ninja"
contact_url: ""
google_tracking_id: ""
google_site_verification: ""
disqus_shortname: ""

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
