title: Jonah Snider
description: > # this means to ignore newlines until "baseurl:"
  Developer, hacker, and high school student
baseurl: ""
url: "https://jonahsnider.ninja"
permalink: /:year/:month/:day/:title

# Extra information
github_profile: "https://github.com/PizzaFox"
author:
  twitter:
    username: thepizzafox
user_email: "me@jonahsnider.ninja"


# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-seo-tag
future: true
include: ["_headers"]