[build]
	base = "./"
  publish = "./out"
	command = "npm run build; npm run export"

# Optional: Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://jonahsnider.netlify.com/*"
  to = "https://jonah.pw/:splat"
  status = 301

# GitHub redirect for my repositories
[[redirects]]
  from = "https://jonah.pw/gh/*"
  to = "https://github.com/pizzafox/:splat"
  status = 301

# Cache Next.js build folder between Netlify builds
[[plugins]]
package = "netlify-plugin-cache-nextjs"
