backend:
  name: git-gateway
media_folder: "assets/images"
collections:
  #
  # Settings
  #
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      # Navbar
      - name: "navigation"
        label: "Navigation Bar"
        file: "_data/navigation.yml"
        fields:
          # Links in navbar
          - name: "items"
            label: "Items"
            label_singular: "Item"
            widget: list
            fields:
              # Display name
              - label: "Title"
                name: "title"
                widget: "string"

              # Target URL
              - label: "URL"
                name: "url"
                widget: "string"

      - name: "settings"
        label: "Site Settings"
        file: "_data/settings.yml"
        fields:
          # Color used in navbar, 404 pages, and the title
          - label: "Color"
            name: "color"
            widget: "select"
            options:
              - { label: "Primary", value: "primary" }
              - { label: "Red", value: "danger" }
              - { label: "White", value: "light" }
              - { label: "Black", value: "dark" }
              - { label: "Blue", value: "link" }
              - { label: "Cyan", value: "info" }
              - { label: "Green", value: "success" }
              - { label: "Yellow", value: "warning" }

          # Brand text
          - label: "Brand"
            name: "brand"
            widget: "string"
   
  #
  # Pages
  #
  - name: "importantPages"
    label: "Important Pages"
    editor:
      preview: false
    delete: false
    files:
        # Home page
        - label : "Home page"
          name: "home"
          file: "index.md"
          fields:
            # Jekyll layout
            - label: "Layout"
              name: "layout"
              widget: "hidden"
              default: "home"

            # Title
            - label: "Title"
              name: "title"
              widget: "string"

            # About me
            - label: "About me"
              name: "aboutMe"
              widget: "object"
              fields:
                - label: "Text"
                  name: "text"
                  widget: "text"

                - label: "Color"
                  name: "color"
                  widget: "select"
                  options:
                    - { label: "Primary", value: "primary" }
                    - { label: "Red", value: "danger" }
                    - { label: "White", value: "light" }
                    - { label: "Black", value: "dark" }
                    - { label: "Blue", value: "link" }
                    - { label: "Cyan", value: "info" }
                    - { label: "Green", value: "success" }
                    - { label: "Yellow", value: "warning" }

            # Subtitle  
            - label: "Subtitle"
              name: "subtitle"
              widget: "string"

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: "General pages"
    folder: "/"
    slug: "{{slug}}"
    create: true
    filter: { field: "layout", value: "page" }
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        tagname: "h1"

      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"

      - label: "Body"
        name: "body"
        widget: "markdown"
